# BNF

program ::= statementLst

statementLst ::= 
    statement | 
    statementLst

statement ::= 
    create type ident | 
    set ident to exp |
    output exp

type ::= 
    'var' | 
    'list' |
ident ::=
    string

exp ::= 
    int |
    string |
    indent |
    exp op exp |

op ::= '+' | '-' | '*' | '/' | '**'

int ::= ['0' - '9']*

string ::= 
    int
    ['a' - 'z', 'A' - 'Z']* |

